### ISSUE TITLE
Docker 容器中的 Cron 未触发，待测试或完善

### ISSUE THREAD

**Issue by beetcb** [ceajs/cea#16]
> 由于默认 cea-cron 只在 6:30 触发，所以下面将用更简单的 cron 来复现问题 

具体复现过程，将 `docker/cea-cron` 改为如下内容：
```bash
* * * * * root echo hello
# empty
```
在 docker 目录一次运行以下命令构建容器：
```bash
sudo docker build -t h .
sudo docker run --name hello_there h
# 几分钟内无任何输出

sudo docker exec hello_there cat /var/spool/cron/crontabs/root
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (./cea-cron installed on Sat Oct 30 22:57:03 2021)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
# * * * * * root echo hello
# An empty line is required at the end of this file for a valid cron file.

sudo docker exec hello_there ps aux
# USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
# root           1  0.0  0.1   3824  2604 ?        Ss   22:58   0:00 cron -f
# root         127  0.0  0.1   5904  2812 ?        Rs   23:09   0:00 ps aux
```
@luckycat0426 ，麻烦帮忙看看？

**Comment by luckycat0426** [comment]
> # An empty line is required at the end of this file for a valid cron file.
cronfile 文件最后要有一个空行

**Comment by beetcb** [comment]
有，不然就构造不了镜像

**Comment by luckycat0426** [comment]
```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
* * * * * echo hello
* * * * * echo "test" >> /tmp/crontest
```
crontab 应该是另起进程执行命令,crontab -f 不会有回显输出,
用该crontab文件测试
```
➜  cea git:(main) ✗ docker exec -ti test bash
root@f1601dab7ca2:/cea# cat /tmp/crontest
cat: /tmp/crontest: No such file or directory
root@f1601dab7ca2:/cea# cat /tmp/crontest^M 
test
root@f1601dab7ca2:/cea# 
```
可以看到crontab成功执行了文件写入操作.
cron未触发是怎么发现的?cea到点没有执行吗

**Comment by luckycat0426** [comment]
https://superuser.com/questions/593423/ubuntu-how-does-cron-execute-jobs

> This answer is for ubuntu. Other linux / unix operating systems may vary slighty.

Every minute the cron daemon reads all the crontab files and loads them into memory. For each cron entry which is to be run (determined by the crontab time fields) cron forks a copy of itself.

The forked cron child process then executes a new shell (typically /bin/sh but this can be overridden) to execute the crontab command. cron itself only forks the child processes that manage the jobs. So the cron entries are run concurrently - if one job takes an hour for example, it will not impact on the execution of any other cron jobs.

Redirection should work as normal and the output file will be written to the $HOME directory of the user who owns the crontab. It some cases it is worth providing the full path to commands and redirected files to avoid issues with PATH and HOME settings.

**Comment by beetcb** [comment]
今天抽时间给容器装 rsyslog 测试了一下，日志显示：
```bash
Nov  2 21:23:01 a9f006f92660 CRON[626]: (CRON) info (No MTA installed, discarding output)
```
证明 `cron -f` 不输出的真正原因是没有消息推送工具推送到 output，那么要使得 `docker logs` 有数据，我们就需要安装邮件工具，所以 dockerfile 加上 sendmail 的安装能解决输出的问题

**Comment by beetcb** [comment]
当然还可以用 #17 的方案，就不用保留输出了

**Comment by beetcb** [comment]
签到未运行的原因是 cron 解释命令为 `cea sign\r`，这样 cea 就无法识别了；因为我是在 Windows 上编辑的这个文件，所以 EOL 为 `\r\n` ，`\r` 在 Unix 上就变成了新字符 😂 @luckycat0426
