### ISSUE TITLE
请求增加PushPlus微信消息推送

### ISSUE THREAD

**Issue by Juaran** [ceajs/cea#17]
>[pushplus](http://pushplus.hxtrip.com/)集成了微信、短信、邮件等实时信息推送平台；
> 你只需要调用简单的API，即可帮助你迅速完成消息的推送，使用简单方便；
> 一切只是为了让推送变的更简单；

这样每天早上打开微信就收到签到成功的通知啦！

哪天版本更新也能及时补签~

**Comment by beetcb** [comment]
会考虑加入推送功能，不过这个 API 是明文传输的（HTTP 协议），数据无法加密

**Comment by beetcb** [comment]
不过我们也不需要推送私密消息，我的顾虑是这个方案相比 [server 酱](https://sct.ftqq.com/sendkey)有什么优势吗？@Juaran

**Comment by Juaran** [comment]
> 不过我们也不需要推送私密消息，我还有一个顾虑是这个方案相比 [server 酱](https://sct.ftqq.com/sendkey)有什么优势吗？@Juaran

微信消息推送都是差不多的，类似的还有[WxPusher](https://wxpusher.dingliqc.com/docs/#/)，但是微信官方对消息模板有限制，公众号推送消息不能直接显示正文内容，需要点开查看（略麻烦，虽然可以把正文作为标题推送），所以目前使用企业微信推送通道的较多，能够直接看到消息内容，但配置起来比第三方推送麻烦些！

**Comment by beetcb** [comment]
所以目前最简单的配置方式就是服务号咯，就用这个吧(虽然有下线风险) (^///^)

**Comment by luckycat0426** [comment]
``` typescript
import { Push } from './push'
const { Signale } = signale

const Sign = new Signale({
  types: {
    error: {
      label: '失败',
    },
    success: {
      label: '成功',
    },
    warn: {
      label: '警示',
    },
  },
} as SignaleOptions)
interface Logtype {
  message: string
  suffix: string
}

export default class Logger {
  private success(
    loginfo: Logtype
  ): void {
    Sign.success({
      message: loginfo.message,
      suffix: loginfo.suffix
    })
    Push(loginfo.message, 'success')
  }
```
想了一个大概思路,修改logger.tx,重载success,error,info 方法,改成推送消息和调用Signale,这样就不用重写其他文件调用logger的方式,我对typescript不太熟悉,请教一下这样是否正确. @beetcb

**Comment by beetcb** [comment]
语法不是问题（即便不是最佳实践），我可以 review 修改
有个问题， push 函数如何实现呢？他被调用了多次，如何保证只发送一次签到结果呢 @luckycat0426

**Comment by luckycat0426** [comment]
刚开始想的是所有消息都推送过去,如果要实现只发送一次的话,可以在push中想办法存起来,在最后执行完调用推送,这些可以在push函数中用用户配置字段控制.到时候想要加入新的推送手段也可以修改push函数添加.

**Comment by beetcb** [comment]
可以，本来是可以直接拿这个变量推送的

https://github.com/ceajs/cea/blob/eae221ecaf1329810876c718b496e0ce5a9a5dc4/plugins/check-in/src/index.ts#L242-L244

但是为了统一设计，给其它插件提供一个统一的日志输出|推送功能，把他封装到 cea-core 更好

现在问题就剩下如何保存消息数据了，初步的想法是所有 `log.xxx()` 输出的调用都会被保存起来，最后调用 `log.push()` 触发推送？有更好的建议吗？

**Comment by beetcb** [comment]
https://github.com/ceajs/cea/commit/2c9a5d73e6620acfef91f19bd37dc709297a3ae3 已完成，只差更新文档 @luckycat0426  @Juaran

**Comment by beetcb** [comment]
文档已更新 https://github.com/ceajs/cea/blob/main/docs/config.md
