### ISSUE TITLE
增加Pushplus消息一对多推送

### ISSUE THREAD

**Issue by Juaran** [ceajs/cea#23]
当前ceajs消息推送方式为一对一推送，API如下：

```
http://pushplus.hxtrip.com/send?token=xxx&title=XXX&content=XXX&template=html
```

项目当前支持多用户签到，当然少不了消息一对多推送，API如下：

```
http://pushplus.hxtrip.com/send?token=xxx&title=XXX&content=XXX&template=html&topic=XXX
```

使用时需要在Pushplus中添加群组并添加群成员，API仅增加topic参数（群组名称）

具体地，代码notifier.js中POST表单参数增加topic参数（为空时即1对1推送）

配置中notifier数组增加元素topic，默认为空，不为空则为一对多推送

**Comment by beetcb** [comment]
OK，明天我试一下，跟 API 功能版本一起发布

**Comment by beetcb** [comment]
新版已发布，详情可参考配置文档 @Juaran
