### ISSUE TITLE
特殊边缘情形：滑动条块验证

### ISSUE THREAD

**Issue by philhsu1995** [ceajs/cea#25]
<img width="263" alt="Snipaste_2021-11-25_23-35-56" src="https://user-images.githubusercontent.com/49578509/143471099-09fdf765-4168-43b7-b5d1-819dfbe2adbb.png">

- 个别学校统一登陆页面为滑动条块验证，不能完成登陆验证，是否可以绕行或另有良策呢

**Comment by beetcb** [comment]
今天写了两个 MVP，分别是原生图片处理、结合 opencv 的模板匹配
用 `Playwright` 用你们学校测试（1000 次测试）：
1. 原生图片处理，速度块、可信度低 578 / 1000
```bash
Running 1000 tests using 4 workers
  ...
  578 passed (24m)
```
2. 结合 opencv，速度慢、可信度高 728 / 1000
```
Running 1000 tests using 4 workers
  ...
  728 passed (49m)
```

目前准备牺牲运行时间，用准确点的 2 方案，用插件实现

@philhsu1995

**Comment by beetcb** [comment]
可信度提不上去的根本原因是没办法拿到原图（API 只返回了滑块背景图和滑块图），也就无法拿原图与滑块背景图比对区分，只能用其它笨方法

**Comment by beetcb** [comment]
通过 https://github.com/ceajs/slider-captcha  解决了，你可以 Pull 最新的代码编译测试，或者发邮件我帮你测试下 @philhsu1995

**Comment by philhsu1995** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    厉害啊大佬，感激涕零！恐怕需要你帮忙测试，我虽然也是闲余之时作为娱乐感觉很有趣，只是我一学经济学的java小白，编译测试这事还真有点为难我胖虎，我把我的账号暂时提供给你测试可否？用户名：21011020004密码：Thankyou48o
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年12月4日 ***@***.***> 写道： 




通过 https://github.com/ceajs/slider-captcha  解决了，你可以 Pull 最新的代码编译测试，或者发邮件我帮你测试下 @philhsu1995

**Comment by beetcb** [comment]
帮你删掉敏感信息啦，放在 GitHub 是比较危险的 @philhsu1995

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/144735025-4fdb4327-3e01-4c1f-a1d3-d220f915f771.png)

解决！等下更新后的配置文件说明中会有 `retry` 字段，也就是防止滑动识别失败备用登录的次数 @philhsu1995

**Comment by philhsu1995** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    嗷好的呢，我忘了这是直接回复到github呢，感谢大佬！太赞了！
