### ISSUE TITLE
添加用户报错

### ISSUE THREAD

**Issue by djkcyl** [ceajs/cea#26]
![Screenshot_20211129-010638.jpg](https://user-images.githubusercontent.com/59153990/143778345-7af79ea5-52f0-44d7-811f-7d7bceeb008f.jpg)![Screenshot_20211129-010633.jpg](https://user-images.githubusercontent.com/59153990/143778346-32c5ecde-7114-412f-b3e5-01f87c70db2d.jpg)

**Comment by beetcb** [comment]
学校id错误或那个API的网络不稳，建议再试一遍

https://cea.beetcb.com/ -> 用于查询学校 id

@djkcyl

**Comment by djkcyl** [comment]
> 

可以了，这id真离谱
