### ISSUE TITLE
需要添加指定配置文件的路径选项

### ISSUE THREAD

**Issue by allinu** [ceajs/cea#27]
当前版本没有办法指定config的路径只能使用当前目录的配置文件和全局的配置文件，但是我现在有一个就是，需要指定配置文件或者直接更改默认配置文件路径的需求。希望能添加这个功能，或者告知默认配置文件的路径

**Comment by beetcb** [comment]
可以，下个版本会加进来 @allinu

**Comment by allinu** [comment]
好的，那我就拭目以待啦

**Comment by beetcb** [comment]
@allinu 更新啦
