### ISSUE TITLE
福建农林大学无法登录成功，需适配

### ISSUE THREAD

**Issue by linrusheng123** [ceajs/cea#30]
https://fafu.campusphere.net/portal/login

作者大大   按照教程网页源代码也只有一个表单数据  而且只用输入验证码   不知道为什么登录不上去
 
日志的报错也是千奇百怪的   有点头大  望能解决
![QQ截图20211207221710](https://user-images.githubusercontent.com/37946749/145045791-31c51fb2-5433-4c78-bf2c-1221cf2f18eb.png)

![QQ截图20211207221718](https://user-images.githubusercontent.com/37946749/145045866-0e7b319c-0d39-40bd-a4ec-0958d4cb7382.png)
![QQ截图20211207221727](https://user-images.githubusercontent.com/37946749/145045894-b00c8a94-3ec8-4db5-8fc3-d29671a8495a.png)

![QQ截图20211207221745](https://user-images.githubusercontent.com/37946749/145045909-a0634cdf-9392-49aa-ba4c-757e2396152f.png)

**Comment by linrusheng123** [comment]
若需要我的账号密码我可以提供  我有验证过  账号密码是没错的

**Comment by beetcb** [comment]
我 Merge 掉 #31 你再试试 @linrusheng123  ？

**Comment by beetcb** [comment]
默认的 formIdx 是 2，所以登录不上是正常的
> 比如我搜索到了四个结果，用户名密码登录表单在第二个，那么就能得到 formIdx 的值为 1，将此值与 NOTCLOUD 对象中的同字段值比对，有差异则需要在边缘情形文件中增加对于学校的边缘情形

**Comment by linrusheng123** [comment]
![屏幕截图 2021-12-08 123321](https://user-images.githubusercontent.com/37946749/145148720-e0d7cd87-2d99-4aaf-93d3-2f9ed6dbc044.png)
重新部署后目前是这个情况  可能是表单是1  我再去提交一下pr   辛苦了作者大大

**Comment by beetcb** [comment]
我看了看，是因为提交登录表单时，需要用 captchaResponse 作为 key，所以要单独指定 `submitCaptchakey`，这个确实没在 #20 里面提到，默认了 @linrusheng123 

https://github.com/ceajs/cea/blob/de925add01739dbfc8c7de8573be162a8c3b5713/src/core/src/crawler/login.ts#L132-L139

**Comment by linrusheng123** [comment]
所以应该是添加一行
"submitCaptchakey": "captchaResponse"
这个吗

**Comment by linrusheng123** [comment]
![屏幕截图 2021-12-08 180326](https://user-images.githubusercontent.com/37946749/145189266-bba58ac8-5b27-4240-8944-ad526ee2b2f1.png)
![屏幕截图 2021-12-08 180427](https://user-images.githubusercontent.com/37946749/145189288-33ea0038-400a-4b68-b313-c82f8e06e2f5.png)
作者大大   对一键部署不是很明白  我看您更改了我仓库Fork的文件 就按照图一改成那样了 然后部署完后  日志是图二  而且返回值还是null

**Comment by linrusheng123** [comment]
![屏幕截图 2021-12-08 181423](https://user-images.githubusercontent.com/37946749/145190697-c6f12c98-bf8b-46da-a257-a378dce4c32a.png)
您刚刚说的指定captchaResponse这个是按照这个指定为xyzd吗

**Comment by beetcb** [comment]
不 🤣，我已经改好了，你不需要修改的，还是登不上证明需要更深程度的测试，麻烦（发我邮箱）给个测试账号

**Comment by linrusheng123** [comment]
![屏幕截图 2021-12-08 182655](https://user-images.githubusercontent.com/37946749/145192492-d4bad928-c66c-4c9e-9b44-69c31cc44677.png)
这是提交的表单数据

**Comment by linrusheng123** [comment]
好的 我现在发您邮箱

**Comment by linrusheng123** [comment]
个人简介没看到邮箱hhh  我就发这吧  您收到后我删除
账号是  3206101136
密码是  okl123okl
代号是 fafu

[[users]]
username = "3206101136"
password = "okl123okl"
alias = "one"
addr = ["119.189574","26.060297", "福州市闽侯县源江路(福建农林大学海峡联合学院)"]
school = "fafu"

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/145204662-44cb217b-554a-4fe2-b7ba-466254fda935.png)

我都还没改，现在登录是没问题的，除非验证码识别错误

然后你在腾讯云的话建议重新部署下，并且配置一下登录重试次数 @linrusheng123

**Comment by beetcb** [comment]
说实话，自动识别验证码准确度挺低的，我也没想到会这么低，滑块验证码倒是高得多 😂

**Comment by linrusheng123** [comment]
嗯  那我现在部署一下试试  就是用你的仓库地址吧

**Comment by linrusheng123** [comment]
晕  还是不行hhhh  我试试部署到我的服务器去

**Comment by beetcb** [comment]
> 晕 还是不行hhhh 我试试部署到我的服务器去

我发现一个 Bug，自动识别图片验证码，它用的错误的照片

手动是能登陆的，目前这个版本肯定不能自动识别了 (●'◡'●)

 @linrusheng123

**Comment by linrusheng123** [comment]
我刚刚发现  用命令行一下就登录成功了   ; )

**Comment by linrusheng123** [comment]
那 目前有什么办法能实现每天定点自动签到和查寝吗  有一台windows系统的天翼云服务器

**Comment by beetcb** [comment]
试过了，改掉两行代码就行，不过我有点好奇现在的识别为啥是错的，所以会在 Dig 一下看看

**Comment by beetcb** [comment]
![image](https://user-images.githubusercontent.com/63141491/145212730-b671e1b3-8754-4dc3-b27d-a341f394220e.png)

新版本会修复，但是这准确率 ... 可能不太行

@linrusheng123

**Comment by linrusheng123** [comment]
那等新版本吗  ；）  可以使用了方便提醒一下不

**Comment by beetcb** [comment]
@linrusheng123 迟到好久的更新，终于到了 😂

**Comment by linrusheng123** [comment]
@beetcb 哈哈哈哈哈哈哈哈哈哈哈哈哈哈好的  辛苦了！！

**Comment by linrusheng123** [comment]
已完成了   腾讯云函数还是很不稳定 华侨大学的滑块验证无法通过 而且会出现进行到一半然后停止运行的情况 就是登陆完就没后续了 个人感觉是腾讯云函数的免费资源供不起代码的运行 但在高配置的本地电脑上完美运行   之后转移到服务器端  加上windows的定时任务  期待明天的表现😆

**Comment by beetcb** [comment]
昨天我都没更新云函数（刚刚才更新），虽然可能出现你说的算力不够的问题，还是建议重新部署试下 @linrusheng123

**Comment by linrusheng123** [comment]
发现一个令人崩溃的事实hhhh
我们学校日常的是  信息收集 
大大有空方便适配下吗  
我看在同类型里也有这个功能
🥺🥺🥺

**Comment by beetcb** [comment]
哪种，方便截图吗？

**Comment by linrusheng123** [comment]
![Screenshot_20211214_112800_com.wisedu.cpdaily.jpg](https://user-images.githubusercontent.com/37946749/145927975-8ec8ff22-83ca-4301-aa67-ccfa7c842be1.jpg)
这样的
![Screenshot_20211214_112929.jpg](https://user-images.githubusercontent.com/37946749/145928013-d3428195-3511-4864-9b1a-94360d5f399f.jpg)

**Comment by beetcb** [comment]
如果能看到信息收集历史就很好实现了，用之前填过的数据就行，麻烦你看看有没有类似历史签到的功能？

**Comment by linrusheng123** [comment]
有的   每天只需点进去  它会自动按照上一次填写的信息自动填好表格 最底下有个定位 （如图） 人工每日操作只需打开app - 点击信息收集- 往下滑点击提交就可以  
![image](https://user-images.githubusercontent.com/37946749/145934335-db3f25db-8510-4fd6-abd0-01d8fab377bd.png)

**Comment by beetcb** [comment]
ok，有时间实现这个插件，和查寝非常相似 @linrusheng123

**Comment by beetcb** [comment]
信息收集适配进度请关注 https://github.com/ceajs/cea/issues/38
