### ISSUE TITLE
福州大学登录失败

### ISSUE THREAD

**Issue by logerkta** [ceajs/cea#34]
![5KEN(G11KB3KK{}RFDL I76](https://user-images.githubusercontent.com/70771104/145337957-3de693d2-bc1f-4b61-b61b-03ffaaa65c92.png)
我可以提供账号密码

**Comment by beetcb** [comment]
@logerkta 试着用 #20 的方法尝试一下？

**Comment by beetcb** [comment]
@logerkta 试着用 #20 的方法尝试一下？

**Comment by logerkta** [comment]
和默认值是一样
![~%Q SH_60$N4EF53QN6{UTJ](https://user-images.githubusercontent.com/70771104/145392462-3126c615-7985-493b-a75b-d34f6c53b123.png)
不行啊

**Comment by beetcb** [comment]
还有 `submitCaptchakey`，看了吗。不行的话账号发我邮箱我试试 🥲

**Comment by logerkta** [comment]
看了不行，我发邮箱了

**Comment by xyr365** [comment]
> 看了不行，我发邮箱了

哥解决了吗

**Comment by beetcb** [comment]
最近没时间看，再等等吧 :-( @xyr365

**Comment by beetcb** [comment]
Dup #18
