### ISSUE TITLE
历史月份的优化问题 signedDataMonth

### ISSUE THREAD

**Issue by allinu** [ceajs/cea#36]
您好，现在我就是有这样一个需求，就是把它使用docker 部署然后定时load 配置文件，然后定时执行，现在还有很多的地方没有整理明白，大致如下

1. 多人使用，配置文件中的用户如何加载不同的签到日期
2. 签到日期能否具体一些，是按照什么样的顺序和规律读取已经签到的信息

**Comment by beetcb** [comment]
你不明白签到月份的配置是吧！
1. 目前 cea 的设计是只能全局配置月份，不能单个用户配置，你说的这种情况确实合理，下版本会加上去，欢迎 PR
2. 签到月份是需要查寝或信息收集时需要的，这个字段的主要目的就是减少信息收集表单或者查寝图片的配置，只签到可以忽略，它的查找逻辑就是从该月份的第一天开始，找到第一个成功的签到就停止，也就用这次数据

目前如果要实现这个功能的话，那就跑两个 docker 实例吧，而且需要改一下我们提供的 cron ，我们那个是没有 load 功能的 

@allinu

**Comment by beetcb** [comment]
文档里最后那个例子吧，确实是写错了 🤸，以这个数据结构为准

```ts
type UsersConf = {
  readonly notifier?: [`${number}`, string, string]
  readonly localEdgeCasesFile: string
  readonly users: Array<UserConfOpts>
}

type UserConfOpts = {
  addr: [''] | [string, string, string]
  readonly username: string
  readonly password: string
  readonly alias: string
  readonly school: string
  readonly retry?: number
  readonly captcha?: 'MANUAL' | 'OCR'
  readonly signedDataMonth?: `${number}-${number}`
}
```

**Comment by allinu** [comment]
好的，谢谢

**Comment by allinu** [comment]
@beetcb 你好，我觉得这个使用历史记录的功能的逻辑不太正确，应该从最后一次的成功提交开始查找
如果我想使用历史提交功能，我就只需要，自己再主动提交一次就可以了，但是如果从每月第一次来说的话，如果我想使用这个功能，就需要在等一个月，因为往往每月第一次，与当前需求变动较大

**Comment by beetcb** [comment]
合理 👍，等实现信息收集插件的时候考虑进去
目前来说查寝变动不大，还是能正常使用

**Comment by allinu** [comment]
@beetcb 好的，谢谢

**Comment by allinu** [comment]
谢谢（ღ( ´･ᴗ･` )比心）

**Comment by beetcb** [comment]
那这个 issue 就用来 track 历史月份的优化问题吧，麻烦你修改一下标题，谢谢

**Comment by allinu** [comment]
好的
