### ISSUE TITLE
配置载入问题

### ISSUE THREAD

**Issue by DazeCake** [ceajs/cea#42]
我尝试载入一个自定义配置，其内容为示例内容
```
[[users]]
username = "11"
password = "11"
alias = "one"
addr = [""]
school = "whpu"
```
但是很奇怪的是，似乎它无法被cea载入
![](https://cdn.jsdelivr.net/gh/DazeCake/image-host/blog20220322205636.png)
实际上我也没找到默认的`conf.toml`
![](https://cdn.jsdelivr.net/gh/DazeCake/image-host/blog20220322210005.png)
我使用的环境为`node: v16.0.0` `Ubuntu 20.04` 并以命令行形式安装cea，希望可以得到帮助，不胜感激！

**Comment by DazeCake** [comment]
似乎不使用绝对路径可以载入

**Comment by beetcb** [comment]
是的，目前确实只考虑到了相对路径的情况

https://github.com/ceajs/cea/blob/4744105dd9f4b2ca9a778b80737adb048147e6ff/src/core/src/conf.ts#L19

后面可能会完善下绝对路径 @DazeCake

**Comment by DazeCake** [comment]
感谢您的解答，现在我可以正确载入配置了:D

**Comment by beetcb** [comment]
不客气

**Comment by beetcb** [comment]
新 patch 版本 cea@2.5.8 已修复 @DazeCake
