### ISSUE TITLE
查寝报错

### ISSUE THREAD

**Issue by wyttle** [ceajs/cea#51]
'无法获取历史签到数据作为模板，请检查 signedDataMonth 配置'
正常使用一个月后，昨天开始提示这个。
[[users]]
username = “”
password = ""
alias = ""
addr = [""]
school = "ebbfd1bd-b46e-4a42-ba37-989071c1ed0d"
signedDataMouth="2022-04"

查寝功能正常

**Comment by beetcb** [comment]
好奇怪，修改 `signedDataMouth` 也是这个错误吗？

**Comment by wyttle** [comment]
是的,我发现是签到任务多了一个不需要签到的.
需要自动签到的在下面

**Comment by beetcb** [comment]
em 我们是默认获取未签第一项的，这也应该是原因

**Comment by beetcb** [comment]
? 解决了还是？

**Comment by wyttle** [comment]
解决了 未获取是昨天没签 
签到我直接改数组的第二项就能签上了
