### ISSUE TITLE
编辑用户保存后报错

### ISSUE THREAD

**Issue by RenChengHaoGe** [ceajs/cea#54]
报错内容：API获取Edge-Cases失败

**Comment by beetcb** [comment]
https://github.com/ceajs/cea/blob/d22b13f2ad1ec9892e34fff2d0d19ee744661b10/src/core/src/conf.ts#L89-L93

已复现，依赖的这个 API 挂了 @RenChengHaoGe

**Comment by RenChengHaoGe** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by beetcb** [comment]
已恢复上游接口
